apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: kubernetes-first-deploy
build:
  artifacts:
    - image: mickey-mouse
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - todo-k8s.yaml
